config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'homes#index'
  get 'welcome', to: 'users#welcome'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :password ,presence: true,
	             length:{minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def new
  end
 
  def create 
    if @user=User.find_by(email: params[:email])
  	  if @user.password == params[:password]
  		  session[:user_id]=@user.id
  		  if @user.email=="admin@gmail.com"
  			  redirect_to users_path
  		  else
         flash[:success] ="user successfully logged in"
  		   redirect_to  welcome_path
  	    end
  	  else 
  		  flash.now[:failure] =" password is not match"
        render 'new'
       end
  	else
      flash.now[:failure] =" username is not match"
	    render 'new'
  	end
  end
  
  def destroy 
    session[:user_id]=nil
    flash.now[:success]="user is successfully logged out"
    redirect_to  root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user=User.new
  end
  
  def edit
    @user=User.find(params[:id])
  end
  
  def show
    if session[:user_id] !=nil
      @user=User.find(params[:id])
    else
      flash[:failure] ="Invalid url"
      redirect_to root_path
    end
  end
  
  def index
    if session[:user_id] !=nil
      @user_auth=User.find(session[:user_id])
      if(@user_auth.email=="admin@gmail.com")
        @user=User.all
      else
        flash[:failure] ="Invalid url"
        redirect_to root_path
      end
    else
      flash[:failure] ="Invalid url"
      redirect_to root_path
    end
  end

  def create
    if User.find_by(:email=>params[:user][:email])
      redirect_to new_user_path
      flash[:failure] ="email already exists"
    else
      @user=User.new(user_params)
      if(@user.save)
        redirect_to login_path
        flash[:success] ="User Registered Successfully"
      else
        render 'new'
       end
    end
  end
 
  def update
    @user=User.find(params[:id])
    if(@user.update(user_params))
      redirect_to users_path 
      flash[:success]="Updated Successfully"
    else
      render 'edit'
    end
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="well">
<h2>Welcome#home_page</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Blog</title>
        <%= javascript_include_tag :defaults %> 
        <%= javascript_include_tag :application %>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag   'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    </head>

      <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
             </button>
              <a class="navbar-brand" href="#">My_App</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
              <%if session[:user_id] !=nil %>
                <ul class="nav navbar-nav navbar-right">
                  <li> <%=link_to "logout",logout_path%></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li> <%=link_to "View Profile",user_path(session[:user_id])%></li>
                </ul>
              <%else%>
                <ul class="nav navbar-nav navbar-right">
                  <li> <%=link_to "Register",new_user_path%></li>
                </ul>
                <ul class="nav navbar-nav navbar-right ">
                  <li> <%=link_to "login",login_path%></li>
                </ul>
              <%end%>
              <ul class="nav navbar-nav navbar-right">
                <li> <%=link_to "Home",root_path%></li>
              </ul>
            </div><!--/.nav-collapse -->
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <% flash.each do |a,b| %>
            <%if a=="success"%>
              <div class ="alert alert-success"><%= b%></div>
            <%else%>
              <div class ="alert alert-danger"><%= b%></div>
            <%end%>
          <%end%>
          <%=yield%> 
        </div>
      </div>
      <style>body{
        padding-top:70px;
      }</style>
    </body>
</html>

app/views/users/edit.html.erb
<h1>Edit  User</h1>
<%=form_for :user, url: user_path(@user), method: :patch do |f| %>
  <% if @user.errors.any? %>
    <ul>
      <div class="alert alert-danger">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    </ul>
  <% end %>
  <div class="col-md-8 col md-offset-3 well">
    <p>
      <%= f.label :name %><br>
      <%=f.text_field(:name, {:class=>'form-control'}) %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%=f.text_field(:email, {:class=>'form-control'}) %>
    </p>
    <p>
      <%=f.submit({:class=>"btn btn-primary"})%>
    </p>
     <%=link_to "back", users_path, :class =>'btn btn-default'%>
  </div>
<%end%>

    

app/views/users/index.html.erb
<% @user.each do|user|%>
  <%next if user.email=="admin@gmail.com"%>
  <div class="well">
    <table height="80" width="50%" border="0" cellspacing="0">
      <tr>
        <th>Name</th>
        <td><%=user.name%></td>
      </tr>
      <tr>
        <th>Eamil</th>
        <td><%=user.email%></td>
      </tr>
    </table>
    <%=link_to "view", user_path(user), :class =>'btn btn-default'%>
    <%=link_to "edit", edit_user_path(user), :class =>'btn btn-default'%>
    <%=link_to "Delete",user_path(user), 
                      method: :delete,
                      data: {confirm: 'are you sure?'},
                      :class =>'btn btn-danger'%>

   </div>
<%end%>

app/views/users/new.html.erb
<%=form_for @user, url: users_path,method: :post do |f| %>
  <% if @user.errors.any? %>
    <ul>
      <div class="alert alert-danger">
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    </ul>
  <% end %>
  <h1>New user</h1>
    <div class="col-md-8 col md-offset-3 well">
      <p>
        <%= f.label :name %><br>
        <%=f.text_field(:name, {:class=>'form-control'}) %>
      </p>
      <p>
        <%= f.label :email %><br>
        <%=f.text_field(:email, {:class=>'form-control'}) %>
      </p>
      <p>
        <%= f.label :password %><br>
        <%=f.password_field(:password, {:class=>'form-control'}) %>
      </p>
      <p>
        <%=f.submit({:class=>"btn btn-success"})%>
      </p>
    </div>
<%end%>

app/views/users/show.html.erb
<%@cur_user=User.find(session[:user_id]) %>
<%if @cur_user.email=="admin@gmail.com"|| @user.id ==session[:user_id] %>
  <div class="row">
    <div class="col-md-6 col md-offset-3">
      <h1>profile</h1>
      <table class="table">
        <tr>
          <th>Name</th>
          <td><%=@user.name%></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%=@user.email%></td>
        </tr>
      </table>
      <%@user=User.find(session[:user_id])%>
      <%if @user.email=="admin@gmail.com"%>
        <%=link_to "back", users_path, :class =>'btn btn-default'%>
      <%end%>
    </div>
  </div>
<%else%>
  <h3>unauthorized access..........</h3>
  <%=link_to "back", root_path, :class =>'btn btn-default'%>
<%end%>

app/views/users/welcome.html.erb
<% @user=User.find(session[:user_id])%>
<h1>Haiii.......<%=@user.name%></h1>